package usecase

import (
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestClassifyExtractionNoise(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		fact string
		want []string
	}{
		// Diff fragments
		{name: "added line with no space", fact: "+def _required_env(name):", want: []string{"diff_fragment"}},
		{name: "removed line with no space", fact: "-old_helper()", want: []string{"diff_fragment"}},
		{name: "added line tab indented", fact: "+\tfunc handler(ctx context.Context) {", want: []string{"diff_fragment"}},
		{name: "added line two-space indented", fact: "+  func main() {", want: []string{"diff_fragment"}},
		{name: "removed line two-space indented", fact: "-  oldHelper()", want: []string{"diff_fragment"}},
		{name: "hunk header", fact: "@@ -1,3 +1,5 @@", want: []string{"diff_fragment"}},
		{name: "diff command header", fact: "diff --git a/foo b/foo", want: []string{"diff_fragment"}},
		{name: "file header plus", fact: "+++ a/foo.go", want: []string{"diff_fragment"}},
		{name: "file header minus", fact: "--- a/foo.go", want: []string{"diff_fragment"}},
		{name: "binary diff", fact: "Binary files a/foo and b/foo differ", want: []string{"diff_fragment"}},
		// Markdown bullets must NOT be treated as diff fragments
		{name: "single-space plus markdown bullet", fact: "+ list item", want: nil},
		{name: "single-space minus markdown bullet", fact: "- todo item", want: nil},

		// Generated code markers (and combined with diff)
		{name: "generated code mockgen", fact: "+// Code generated by MockGen. DO NOT EDIT.", want: []string{"diff_fragment", "generated_code"}},
		{name: "generated code do not edit", fact: "// DO NOT EDIT this file", want: []string{"generated_code"}},
		{name: "generated japanese", fact: "// 自動生成ファイル", want: []string{"generated_code"}},

		// Standalone commands
		{name: "git pull command", fact: "git pull --ff-only origin main", want: []string{"standalone_command"}},
		{name: "go test command", fact: "go test ./...", want: []string{"standalone_command"}},
		{name: "make build command", fact: "make build", want: []string{"standalone_command"}},
		{name: "gh pr list command", fact: "gh pr list --state open", want: []string{"standalone_command"}},
		{name: "cd command", fact: "cd /tmp", want: []string{"standalone_command"}},

		// Review-only conclusions
		{name: "must findings none", fact: "MUST findings: none", want: []string{"review_conclusion"}},
		{name: "must findings none with short scope", fact: "MUST findings: none for this round", want: []string{"review_conclusion"}},
		{name: "must findings none with punctuation", fact: "MUST findings: none.", want: []string{"review_conclusion"}},
		{name: "no issues found", fact: "No issues found.", want: []string{"review_conclusion"}},
		{name: "no issues no suffix", fact: "No issues", want: []string{"review_conclusion"}},
		{name: "no problems detected", fact: "No problems detected", want: []string{"review_conclusion"}},
		{name: "lgtm", fact: "LGTM", want: []string{"review_conclusion"}},
		{name: "lgtm with punctuation", fact: "LGTM!", want: []string{"review_conclusion"}},
		{name: "approved", fact: "Approved.", want: []string{"review_conclusion"}},
		{name: "all clear", fact: "All clear", want: []string{"review_conclusion"}},
		{name: "ship it", fact: "Ship it", want: []string{"review_conclusion"}},
		{name: "japanese problem none", fact: "問題なし", want: []string{"review_conclusion"}},
		{name: "japanese confirmed problem none with desu", fact: "確認済み・問題なしです", want: []string{"review_conclusion"}},
		{name: "japanese OK desu", fact: "OKです", want: []string{"review_conclusion"}},
		// Durable continuations after a review-conclusion phrase must NOT be hidden
		{name: "lgtm with durable continuation", fact: "LGTM and we should also reorganize the test layout", want: nil},
		{name: "approved with durable follow-up", fact: "Approved but flag it for follow-up next sprint", want: nil},
		{name: "no issues found with durable continuation", fact: "No issues found in production but check staging carefully", want: nil},
		{name: "no issues with substantive trailing", fact: "No issues right now, but the migration script must be re-run after the v2 deploy", want: nil},
		{name: "must findings none with durable continuation", fact: "MUST findings: none yet, but the security review is still pending downstream", want: nil},

		// Work declarations
		{name: "i will read", fact: "I will read foo.go", want: []string{"work_declaration"}},
		{name: "i'll check", fact: "I'll check the docs", want: []string{"work_declaration"}},
		{name: "let me look", fact: "Let me look at the source", want: []string{"work_declaration"}},
		{name: "lets go", fact: "Let's go", want: []string{"work_declaration"}},
		{name: "going to investigate", fact: "Going to investigate the failure", want: []string{"work_declaration"}},
		{name: "i need to update", fact: "I need to update the config", want: []string{"work_declaration"}},
		{name: "japanese korekara", fact: "これから foo を実装します", want: []string{"work_declaration"}},
		// Work-declaration prefixes paired with a durable signal must NOT be hidden
		{name: "lets use durable choice", fact: "Let's use ContextUsecase for handoff output", want: nil},
		{name: "ill prefer durable choice", fact: "I'll prefer Go over Python in this codebase", want: nil},
		{name: "i will adopt durable choice", fact: "I will adopt the new linter config across all repos", want: nil},
		{name: "i need to always", fact: "I need to always run gofmt before committing", want: nil},
		{name: "let me never", fact: "Let me never push directly to main again", want: nil},

		// Transient PR / Round chatter
		{name: "round 3", fact: "Round 3:", want: []string{"transient_pr_round"}},
		{name: "round 1 follow up", fact: "Round 1 follow-up: cleanup", want: []string{"transient_pr_round"}},
		{name: "pr review pass", fact: "PR #840 review pass", want: []string{"transient_pr_round"}},
		{name: "pr 123 status", fact: "PR 123 status update", want: []string{"transient_pr_round"}},

		// High-signal facts (no noise)
		{name: "preference fact", fact: "Please respond in Japanese", want: nil},
		{name: "decision fact", fact: "Use ContextUsecase for handoff output", want: nil},
		{name: "constraint fact", fact: "Never merge before Codex review", want: nil},
		{name: "lesson fact", fact: "Wait for explicit review completion before merge", want: nil},
		{name: "command in prose stays visible", fact: "Always run go test before merging", want: nil},
		{name: "command mentioned in prose", fact: "Use git pull to fetch updates", want: nil},
		{name: "fact mentions go but is is", fact: "go is a great language for this codebase", want: nil},
		{name: "japanese durable lesson", fact: "次回 Claude Code restart で stale MCP server cache は解消する", want: nil},
		{name: "decision with command argument", fact: "Decided to use --ff-only for pulls in CI", want: nil},
		// Command-prefixed prose statements are durable, not standalone commands
		{name: "go tests require prose", fact: "go tests require a DB connection", want: nil},
		{name: "make build fails prose", fact: "make build fails on Windows", want: nil},
		{name: "git pull works prose", fact: "git pull works only with --ff-only in CI", want: nil},
		{name: "node uses prose", fact: "node uses the package-lock.json from the repo root", want: nil},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := classifyExtractionNoise(tc.fact)
			if diff := cmp.Diff(tc.want, got); diff != "" {
				t.Fatalf("classifyExtractionNoise(%q) mismatch (-want +got):\n%s", tc.fact, diff)
			}
		})
	}
}

func TestIsStandaloneCommand_RejectsProseSentences(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		fact string
	}{
		{name: "go is", fact: "go is a programming language"},
		{name: "git was", fact: "git was the right tool here"},
		{name: "make should", fact: "make should not be invoked manually"},
		{name: "japanese desu", fact: "git pull は CI で実行されます"},
		// Newly classified prose: command name followed by descriptive verb forms
		{name: "go require article", fact: "go tests require a DB connection"},
		{name: "make fails on platform", fact: "make build fails on Windows"},
		{name: "git uses flag", fact: "git uses --ff-only in CI"},
		{name: "node depends on lock file", fact: "node depends on package-lock.json being committed"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := classifyExtractionNoise(tc.fact)
			for _, reason := range got {
				if reason == extractionNoiseStandaloneCommand {
					t.Fatalf("classifyExtractionNoise(%q) should NOT report standalone_command, got %v", tc.fact, got)
				}
			}
		})
	}
}
