version: "2"

linters:
  enable:
    - revive
    - wrapcheck
    - staticcheck
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: "golang.org/x/xerrors"'
      - path: ".*/types/[^/]+\\.go"
        text: "var-naming: avoid meaningless package names"
        linters:
          - revive

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
