# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traceary < Formula
  desc "Local-first CLI and MCP server for AI agent work history"
  homepage "https://github.com/duck8823/traceary"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duck8823/traceary/releases/download/v0.1.10/traceary_0.1.10_darwin_amd64.tar.gz"
      sha256 "39a0145239722971cfc37dc4becb4153018855fe7ad57be24f9936e067d1ceb9"

      define_method(:install) do
        bin.install "traceary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duck8823/traceary/releases/download/v0.1.10/traceary_0.1.10_darwin_arm64.tar.gz"
      sha256 "c563f76380acb8abfdbe7461dbc6ed71ec9b7a1d67e7d2e93247ec48290590ec"

      define_method(:install) do
        bin.install "traceary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duck8823/traceary/releases/download/v0.1.10/traceary_0.1.10_linux_amd64.tar.gz"
      sha256 "62223029ddc50fb590e7604948a3b541564c05a5895b394177dff2e918aeef3b"
      define_method(:install) do
        bin.install "traceary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duck8823/traceary/releases/download/v0.1.10/traceary_0.1.10_linux_arm64.tar.gz"
      sha256 "aae39718555296ed65724ea3451d11f696b8c5669fe486c0da013b4a82e75738"
      define_method(:install) do
        bin.install "traceary"
      end
    end
  end

  test do
    system "#{bin}/traceary", "version"
  end
end
