# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traceary < Formula
  desc "Local-first CLI and MCP server for AI agent work history"
  homepage "https://github.com/duck8823/traceary"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duck8823/traceary/releases/download/v0.21.0/traceary_0.21.0_darwin_amd64.tar.gz"
      sha256 "982a48cdc9db3dc118574e88f56e1b043a7950af5ff59700a8e593ec2880c414"

      define_method(:install) do
        bin.install "traceary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duck8823/traceary/releases/download/v0.21.0/traceary_0.21.0_darwin_arm64.tar.gz"
      sha256 "2b427e18ee6b6194e8395b9c104b70895c64e10d92918e361b05d9b8cf7709b9"

      define_method(:install) do
        bin.install "traceary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duck8823/traceary/releases/download/v0.21.0/traceary_0.21.0_linux_amd64.tar.gz"
      sha256 "19f696049e86ad89f1569c69fd158716f38ec62300c821643cbd002911668116"
      define_method(:install) do
        bin.install "traceary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duck8823/traceary/releases/download/v0.21.0/traceary_0.21.0_linux_arm64.tar.gz"
      sha256 "ee9fc05c7ec37a9cfa58cff5bbd9b07a4a09a064f75353de944d55668a383f54"
      define_method(:install) do
        bin.install "traceary"
      end
    end
  end

  test do
    system "#{bin}/traceary", "--version"
  end
end
